#!/usr/bin/env bash
#Redirecting all requests to /redirect_me

#Installing NginX and setting index.html
apt-get update
apt-get install -y nginx
echo "Hello World!" | /var/www/html/index.html

#Redirect requests to /redirect_me permanently
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me http:\/\/$host permanent;"
sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

service nginx restart
