#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# +==========================================+

# using C-like syntax.

LIMIT=10

for ((a=1; a <= LIMIT ; a++))  # Double parentheses, and naked "LIMIT"
do
  echo "Best School"
done
