#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# at the 9th iteration prints "Best School\nHi"
# +==========================================+

# using C-like syntax.

LIMIT=20
a=1
while ((a <= LIMIT))  # Double parentheses, and naked "LIMIT"
do
  case $a in
    4)
      echo "$a"
      echo "bad luck from China"
      ;;

    9)
      echo "$a"
      echo "bad luck from Japan"
      ;;

    17)
      echo "$a"
      echo "bad luck from Italy"
      ;;

    *)
      echo "$a"
      ;;
  esac

  ((a++))
done
