#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# at the 9th iteration prints "Best School\nHi"
# +==========================================+

# using C-like syntax.

HOUR=12
MINUTE=59
h=0

while ((h <= HOUR))  # Double parentheses, and naked "LIMIT"
do
  echo "Hour: $h"
  m=1
  while ((m <= MINUTE))
  do
    echo "$m"
    ((m++))
  done

  ((h++))
done
