#!/usr/bin/env bash
# Fixes a web server to run Nginx as the nginx user.

# set a user in the config by replacing '#user' and it's value
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# replace port 80 with 8080 in the sites-available config
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# give owner permissions to read and write to the config file
chmod 644 /etc/nginx/nginx.conf

# Stop apache from interfering
pkill apache2

# Starting the nginx server as a nginx user
sudo -u nginx service nginx start
